//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.23 at 07:25:27 PM CEST 
//


package net.edusharing.collections.rlp.xmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bctype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://bsbb.eu}stringtype"/>
 *         &lt;element name="title" type="{http://bsbb.eu}stringtype"/>
 *         &lt;element name="bc1" type="{http://bsbb.eu}textcontent"/>
 *         &lt;element name="bc2" type="{http://bsbb.eu}textcontent"/>
 *         &lt;element name="bc3" type="{http://bsbb.eu}c2type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bctype", propOrder = {
    "id",
    "title",
    "bc1",
    "bc2",
    "bc3"
})
public class Bctype {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected Textcontent bc1;
    @XmlElement(required = true)
    protected Textcontent bc2;
    @XmlElement(required = true)
    protected C2Type bc3;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the bc1 property.
     * 
     * @return
     *     possible object is
     *     {@link Textcontent }
     *     
     */
    public Textcontent getBc1() {
        return bc1;
    }

    /**
     * Sets the value of the bc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Textcontent }
     *     
     */
    public void setBc1(Textcontent value) {
        this.bc1 = value;
    }

    /**
     * Gets the value of the bc2 property.
     * 
     * @return
     *     possible object is
     *     {@link Textcontent }
     *     
     */
    public Textcontent getBc2() {
        return bc2;
    }

    /**
     * Sets the value of the bc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Textcontent }
     *     
     */
    public void setBc2(Textcontent value) {
        this.bc2 = value;
    }

    /**
     * Gets the value of the bc3 property.
     * 
     * @return
     *     possible object is
     *     {@link C2Type }
     *     
     */
    public C2Type getBc3() {
        return bc3;
    }

    /**
     * Sets the value of the bc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link C2Type }
     *     
     */
    public void setBc3(C2Type value) {
        this.bc3 = value;
    }

}
