//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.23 at 07:25:27 PM CEST 
//


package net.edusharing.collections.rlp.xmlclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for btype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="btype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://bsbb.eu}stringtype"/>
 *         &lt;element name="title" type="{http://bsbb.eu}stringtype"/>
 *         &lt;element name="einleitung" type="{http://bsbb.eu}textcontent"/>
 *         &lt;element name="bcs" type="{http://bsbb.eu}bctype"/>
 *         &lt;element name="bcm" type="{http://bsbb.eu}bctype"/>
 *         &lt;element name="ueber" type="{http://bsbb.eu}textcontent" maxOccurs="15"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "btype", propOrder = {
    "id",
    "title",
    "einleitung",
    "bcs",
    "bcm",
    "ueber"
})
public class Btype {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected Textcontent einleitung;
    @XmlElement(required = true)
    protected Bctype bcs;
    @XmlElement(required = true)
    protected Bctype bcm;
    @XmlElement(required = true)
    protected List<Textcontent> ueber;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the einleitung property.
     * 
     * @return
     *     possible object is
     *     {@link Textcontent }
     *     
     */
    public Textcontent getEinleitung() {
        return einleitung;
    }

    /**
     * Sets the value of the einleitung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Textcontent }
     *     
     */
    public void setEinleitung(Textcontent value) {
        this.einleitung = value;
    }

    /**
     * Gets the value of the bcs property.
     * 
     * @return
     *     possible object is
     *     {@link Bctype }
     *     
     */
    public Bctype getBcs() {
        return bcs;
    }

    /**
     * Sets the value of the bcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bctype }
     *     
     */
    public void setBcs(Bctype value) {
        this.bcs = value;
    }

    /**
     * Gets the value of the bcm property.
     * 
     * @return
     *     possible object is
     *     {@link Bctype }
     *     
     */
    public Bctype getBcm() {
        return bcm;
    }

    /**
     * Sets the value of the bcm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bctype }
     *     
     */
    public void setBcm(Bctype value) {
        this.bcm = value;
    }

    /**
     * Gets the value of the ueber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ueber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUeber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Textcontent }
     * 
     * 
     */
    public List<Textcontent> getUeber() {
        if (ueber == null) {
            ueber = new ArrayList<Textcontent>();
        }
        return this.ueber;
    }

}
