//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.17 at 12:55:01 PM CEST 
//


package net.edusharing.collections.rlp.xmlclasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.edusharing.collections.rlp.xmlclasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fach_QNAME = new QName("http://bsbb.eu", "fach");
    private final static QName _C2_QNAME = new QName("http://bsbb.eu", "c2");
    private final static QName _Text_QNAME = new QName("http://bsbb.eu", "text");
    private final static QName _Textc_QNAME = new QName("http://bsbb.eu", "textc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.edusharing.collections.rlp.xmlclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Textcontent }
     * 
     */
    public Textcontent createTextcontent() {
        return new Textcontent();
    }

    /**
     * Create an instance of {@link C2Type }
     * 
     */
    public C2Type createC2Type() {
        return new C2Type();
    }

    /**
     * Create an instance of {@link Fachtype }
     * 
     */
    public Fachtype createFachtype() {
        return new Fachtype();
    }

    /**
     * Create an instance of {@link C3Type }
     * 
     */
    public C3Type createC3Type() {
        return new C3Type();
    }

    /**
     * Create an instance of {@link Competenceareatype }
     * 
     */
    public Competenceareatype createCompetenceareatype() {
        return new Competenceareatype();
    }

    /**
     * Create an instance of {@link Competencetype }
     * 
     */
    public Competencetype createCompetencetype() {
        return new Competencetype();
    }

    /**
     * Create an instance of {@link Stufentype }
     * 
     */
    public Stufentype createStufentype() {
        return new Stufentype();
    }

    /**
     * Create an instance of {@link Standardtype }
     * 
     */
    public Standardtype createStandardtype() {
        return new Standardtype();
    }

    /**
     * Create an instance of {@link Themainhalttype }
     * 
     */
    public Themainhalttype createThemainhalttype() {
        return new Themainhalttype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fachtype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bsbb.eu", name = "fach")
    public JAXBElement<Fachtype> createFach(Fachtype value) {
        return new JAXBElement<Fachtype>(_Fach_QNAME, Fachtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link C2Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bsbb.eu", name = "c2")
    public JAXBElement<C2Type> createC2(C2Type value) {
        return new JAXBElement<C2Type>(_C2_QNAME, C2Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bsbb.eu", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Textcontent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bsbb.eu", name = "textc")
    public JAXBElement<Textcontent> createTextc(Textcontent value) {
        return new JAXBElement<Textcontent>(_Textc_QNAME, Textcontent.class, null, value);
    }

}
