//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.17 at 12:55:01 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bsbb.eu", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.edusharing.collections.rlp.xmlclasses;
