//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.23 at 07:25:27 PM CEST 
//


package net.edusharing.collections.rlp.xmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rlp110type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rlp110type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="a" type="{http://bsbb.eu}atype"/>
 *         &lt;element name="b" type="{http://bsbb.eu}btype"/>
 *         &lt;element name="c" type="{http://bsbb.eu}ctype"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rlp110type", propOrder = {
    "a",
    "b",
    "c"
})
@XmlRootElement(name = "rlp110")
public class Rlp110Type {

    @XmlElement(required = true)
    protected Atype a;
    @XmlElement(required = true)
    protected Btype b;
    @XmlElement(required = true)
    protected Ctype c;

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link Atype }
     *     
     */
    public Atype getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atype }
     *     
     */
    public void setA(Atype value) {
        this.a = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link Btype }
     *     
     */
    public Btype getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link Btype }
     *     
     */
    public void setB(Btype value) {
        this.b = value;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     {@link Ctype }
     *     
     */
    public Ctype getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ctype }
     *     
     */
    public void setC(Ctype value) {
        this.c = value;
    }

}
